/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/layout/AppHeader/index.vue')['default']
    AppIcon: typeof import('./../components/base/AppIcon/index.vue')['default']
    AppProvider: typeof import('./../components/base/AppProvider/index.vue')['default']
    BaseIcon: typeof import('./../components/base/BaseIcon/index.vue')['default']
    BaseProvider: typeof import('./../components/base/BaseProvider/index.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
